apiVersion: v1
kind: Service
metadata:
  name: myhouse-service
spec:
  selector:
    app: myhouse
  ports:
  - protocol: TCP
    port: 80              # port expos√© sur le service
    targetPort: 5000      # port de ton conteneur Flask
  type: ClusterIP         